end sprint 3
GreenVirs/react-burger pull request #4
Opened 2023-04-17 10:01 UTC by GreenVirs

2023-04-17 11:40 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Защита роутов реализована в одном компоненте
- Используется тег `form` с событием `onSubmit`
- После регистрации происходит автоматическая авторизация

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Не авторизованный юзер не должен иметь возможность сделать заказ
- После процедуры восстановления пароля перекидывает на такую вот страницу - 

<img width="847" alt="Снимок экрана 2023-04-17 в 14 24 21" src="https://user-images.githubusercontent.com/60173362/232470614-04f1f829-29dc-41aa-935c-6f05597e97a4.png">

- По тех заданию у роутов `/login`, `reset-password` и других нет в названии пути `auth`.

- На странице профиля не хватает кнопки "отмена".

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-04-17 11:40 UTC, andryxxa93 commented on src/components/app-router/app-router.tsx
> +          <Route path="login" element={<OnlyUnAuth element={<LoginPage />} />} />
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-04-17 11:40 UTC, andryxxa93 commented on src/components/burger-ingredients/ingredient-details/ingredient-details.tsx
> +  const { ingredient } = useSelector<RootState, { ingredient: Ingredient | null }>((state) => {
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-04-17 14:57 UTC, GreenVirs commented on src/components/app-router/app-router.tsx
> +          <Route path="login" element={<OnlyUnAuth element={<LoginPage />} />} />
Я правильно понимаю, что имеется ввиду https://hashrocket.com/blog/posts/managing-react-router-pathnames ?

2023-04-17 14:58 UTC, GreenVirs commented on src/components/burger-ingredients/ingredient-details/ingredient-details.tsx
> +  const { ingredient } = useSelector<RootState, { ingredient: Ingredient | null }>((state) => {
Хорошо, как раз все думал как оптимизировать это и избавиться от RootState в каждом компоненте

2023-04-18 05:43 UTC, andryxxa93 commented on src/components/burger-ingredients/ingredient-details/ingredient-details.tsx
> +  const { ingredient } = useSelector<RootState, { ingredient: Ingredient | null }>((state) => {
Вы избавитесь от него когда типизируете хук `useSelector` - это будет через один спринт.

2023-04-18 05:44 UTC, andryxxa93 commented on src/components/app-router/app-router.tsx
> +          <Route path="login" element={<OnlyUnAuth element={<LoginPage />} />} />
Я имел в виду обычные константы, но такое решение тоже хорошее 😊

2023-04-18 05:49 UTC, andryxxa93 commented
**Необходимо исправить**
- Кнопка логаута перестала работать

2023-04-18 06:32 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-04-19 15:44 UTC, merged